#!/bin/bash
# start-ralph.sh — Launches the token watchdog daemon alongside Ralph.
# Generated by AgentCaddy for quota-sentinel.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WATCHDOG_PID=""

cleanup() {
    if [ -n "$WATCHDOG_PID" ]; then
        kill "$WATCHDOG_PID" 2>/dev/null || true
        wait "$WATCHDOG_PID" 2>/dev/null || true
    fi
    rm -f "$SCRIPT_DIR/TOKEN_STATUS.json" "$SCRIPT_DIR/watchdog.pid"
}
trap cleanup EXIT INT TERM

# Check for central watchdog
CENTRAL_PID_FILE="$HOME/.agentcaddy/watchdog/central.pid"
if [ -f "$CENTRAL_PID_FILE" ] && kill -0 "$(cat "$CENTRAL_PID_FILE")" 2>/dev/null; then
    echo "[watchdog] Central watchdog detected (pid $(cat "$CENTRAL_PID_FILE"))"
    echo "[watchdog] Starting in client mode (no local API polling)..."
else
    echo "[watchdog] Starting in local mode..."
fi

# Start watchdog daemon in background (auto-detects local vs client mode)
python3 "$SCRIPT_DIR/watchdog/watchdog.py" --config "$SCRIPT_DIR/watchdog/config.json" &
WATCHDOG_PID=$!

# Wait a moment for first poll / registration
sleep 3

# Run Ralph via the appropriate framework
echo "[ralph] Starting via Claude Code..."
claude --command ralph

echo "[watchdog] Shutting down..."
