"""Model switcher — proactive provider-aware model switching for OpenCode.

Polls Quota Sentinel and updates opencode.json model assignments before
quota is exhausted, using fallback_models generated by AgentCaddy.

Unlike reactive plugins (opencode-runtime-fallback) that wait for 429 errors,
this switcher:
  - Switches proactively when a provider reaches YELLOW/RED status
  - Lets running agent sessions finish before the quota runs out
  - Restores original models only after the provider has been consistently
    GREEN for several cycles (hysteresis to prevent flapping)
  - Survives restarts via a state file that remembers original assignments
"""

from __future__ import annotations

import json
import logging
import os
import signal
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

_SENTINEL_DATA_DIR = Path.home() / ".local" / "share" / "quota-sentinel"
_SENTINEL_PID_FILE = _SENTINEL_DATA_DIR / "server.pid"
_SENTINEL_LOG_FILE = _SENTINEL_DATA_DIR / "server.log"
_SENTINEL_START_TIMEOUT = 15  # seconds to wait for server to come up

_OC_AUTH_PATH = Path.home() / ".local" / "share" / "opencode" / "auth.json"
_CLAUDE_CREDS_PATH = Path.home() / ".claude" / ".credentials.json"

# Maps opencode auth.json key → Sentinel provider name
_OC_KEY_TO_PROVIDER = {
    "zai-coding-plan": "zai",
    "zai": "zai",
    "github-copilot": "copilot",
    "minimax-coding-plan": "minimax",
    "minimax": "minimax",
    "deepseek-coding-plan": "deepseek",
    "deepseek": "deepseek",
    "bailian-coding-plan": "alibaba",
    "alibaba-coding-plan": "alibaba",
    "dashscope": "alibaba",
    "alibaba": "alibaba",
}

logger = logging.getLogger("model-switcher")

_UA = "quota-sentinel/model-switcher"


# ── HTTP helpers (stdlib only) ──────────────────────────────────────────


def _http(
    url: str,
    method: str = "GET",
    body: dict | None = None,
    headers: dict[str, str] | None = None,
    timeout: int = 5,
) -> dict[str, Any]:
    data = json.dumps(body).encode() if body else None
    hdrs: dict[str, str] = {"User-Agent": _UA}
    if body:
        hdrs["Content-Type"] = "application/json"
    if headers:
        hdrs.update(headers)
    req = urllib.request.Request(url, data=data, headers=hdrs, method=method)
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode())


# ── State ───────────────────────────────────────────────────────────────


@dataclass
class SwitcherState:
    """Persisted switcher state — survives process restarts."""

    # Original model per agent (from first read of opencode.json)
    original_models: dict[str, str] = field(default_factory=dict)
    # Currently active model per agent (may differ from original)
    active_models: dict[str, str] = field(default_factory=dict)
    # When each agent was last switched (ISO timestamp)
    switched_at: dict[str, str] = field(default_factory=dict)

    def save(self, path: Path) -> None:
        tmp = path.with_suffix(".tmp")
        tmp.write_text(
            json.dumps(
                {
                    "original_models": self.original_models,
                    "active_models": self.active_models,
                    "switched_at": self.switched_at,
                },
                indent=2,
            )
            + "\n"
        )
        tmp.rename(path)

    @classmethod
    def load(cls, path: Path) -> "SwitcherState":
        if not path.exists():
            return cls()
        try:
            raw = json.loads(path.read_text())
            return cls(
                original_models=raw.get("original_models", {}),
                active_models=raw.get("active_models", {}),
                switched_at=raw.get("switched_at", {}),
            )
        except (json.JSONDecodeError, OSError):
            return cls()


# ── Core switcher ───────────────────────────────────────────────────────


class ModelSwitcher:
    """Proactively switches OpenCode models based on Quota Sentinel status.

    Args:
        opencode_json: Path to the project's opencode.json.
        sentinel_url: Quota Sentinel base URL (default http://127.0.0.1:7878).
        poll_interval: Seconds between quota checks (default 60).
        recovery_hold: Consecutive GREEN polls required before restoring
                       original model (default 3, prevents flapping).
    """

    def __init__(
        self,
        opencode_json: Path,
        sentinel_url: str = "http://127.0.0.1:7878",
        poll_interval: int = 60,
        recovery_hold: int = 3,
    ) -> None:
        self.opencode_json = opencode_json.resolve()
        self.sentinel_url = sentinel_url.rstrip("/")
        self.poll_interval = max(poll_interval, 10)
        self.recovery_hold = recovery_hold

        self.state_path = self.opencode_json.parent / ".opencode-switcher.json"
        self.state = SwitcherState.load(self.state_path)

        # Per-provider consecutive GREEN poll counter (for hysteresis)
        self._recovery_counter: dict[str, int] = {}

        # Sentinel registration
        self._instance_id: str | None = None
        self._api_key: str | None = None

    # ── opencode.json I/O ─────────────────────────────────────────────

    def _read_config(self) -> dict[str, Any]:
        return json.loads(self.opencode_json.read_text())

    def _write_config(self, config: dict[str, Any]) -> None:
        tmp = self.opencode_json.with_suffix(".tmp")
        tmp.write_text(json.dumps(config, indent=2) + "\n")
        tmp.rename(self.opencode_json)

    def _load_agents(self) -> dict[str, dict[str, Any]]:
        """Return the agent section of opencode.json."""
        return self._read_config().get("agent", {})

    def _init_state(self) -> None:
        """Populate state.original_models from opencode.json if not already set."""
        agents = self._load_agents()
        changed = False
        for name, agent_cfg in agents.items():
            if name not in self.state.original_models and "model" in agent_cfg:
                self.state.original_models[name] = agent_cfg["model"]
                self.state.active_models[name] = agent_cfg["model"]
                changed = True
        if changed:
            self.state.save(self.state_path)

    # ── Auth discovery ────────────────────────────────────────────────

    def _build_auth(self) -> dict[str, Any]:
        """Build auth payload for Quota Sentinel registration.

        Sources (in priority order):
        1. opencode.json provider.options.apiKey (explicit project config)
        2. ~/.local/share/opencode/auth.json (OpenCode shared credentials)
        3. ~/.claude/.credentials.json (Claude OAuth)
        4. gh auth token (GitHub Copilot)
        """
        auth: dict[str, Any] = {}

        # 1. Explicit API keys from project opencode.json
        try:
            config = self._read_config()
            providers_cfg = config.get("provider", {})
            project_auth: dict[str, Any] = {}
            for provider_name, pcfg in providers_cfg.items():
                api_key = pcfg.get("options", {}).get("apiKey", "")
                # Strip {env:VAR} references — those are resolved at runtime by OpenCode
                if api_key and not api_key.startswith("{env:"):
                    project_auth[provider_name] = {"key": api_key}
            if project_auth:
                auth["opencode_auth"] = project_auth
        except (OSError, json.JSONDecodeError, KeyError):
            pass

        # 2. OpenCode shared auth.json (fills in any gaps)
        try:
            oc_auth = json.loads(_OC_AUTH_PATH.read_text())
            merged = dict(auth.get("opencode_auth", {}))
            for key, entry in oc_auth.items():
                if isinstance(entry, dict) and entry.get("key"):
                    provider = _OC_KEY_TO_PROVIDER.get(key, key)
                    if provider not in merged:
                        merged[provider] = entry
            if merged:
                auth["opencode_auth"] = merged
        except (OSError, json.JSONDecodeError):
            pass

        # 3. Claude OAuth credentials
        try:
            raw = json.loads(_CLAUDE_CREDS_PATH.read_text())
            oauth = raw.get("claudeAiOauth", {})
            if oauth.get("accessToken"):
                auth["claude_credentials"] = {
                    "accessToken": oauth["accessToken"],
                    "refreshToken": oauth.get("refreshToken", ""),
                    "expiresAt": oauth.get("expiresAt", 0),
                }
        except (OSError, json.JSONDecodeError, KeyError):
            pass

        # 4. GitHub token for Copilot
        try:
            r = subprocess.run(
                ["gh", "auth", "token"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            if r.returncode == 0 and r.stdout.strip():
                auth["github_token"] = r.stdout.strip()
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass

        return auth

    # ── Auto-start server ─────────────────────────────────────────────

    def _parse_sentinel_addr(self) -> tuple[str, int] | None:
        """Parse host and port from sentinel_url. Returns None if not localhost."""
        try:
            parsed = urllib.parse.urlparse(self.sentinel_url)
            host = parsed.hostname or "127.0.0.1"
            port = parsed.port or 7878
            if host not in ("127.0.0.1", "localhost", "::1"):
                return None
            return host, port
        except Exception:  # noqa: BLE001
            return None

    def _read_pid(self) -> int | None:
        """Read PID from file, return None if missing or stale."""
        try:
            pid = int(_SENTINEL_PID_FILE.read_text().strip())
            # Check process is actually alive
            os.kill(pid, 0)
            return pid
        except (FileNotFoundError, ValueError, ProcessLookupError, PermissionError):
            return None

    def _ensure_server_running(self) -> bool:
        """Start Quota Sentinel server if not running. Returns True when available."""
        addr = self._parse_sentinel_addr()
        if addr is None:
            logger.error(
                "Quota Sentinel not reachable at %s and auto-start only works for localhost",
                self.sentinel_url,
            )
            return False

        host, port = addr

        # Already running (different process, e.g. another project started it)
        if self._sentinel_available():
            return True

        # Check if there's a stale PID file
        existing_pid = self._read_pid()
        if existing_pid is not None:
            logger.warning(
                "PID file points to process %d but server not responding — removing stale PID",
                existing_pid,
            )
            _SENTINEL_PID_FILE.unlink(missing_ok=True)

        # Spawn the server
        _SENTINEL_DATA_DIR.mkdir(parents=True, exist_ok=True)
        log_fh = _SENTINEL_LOG_FILE.open("a")

        logger.info(
            "Starting Quota Sentinel at %s:%d (log: %s)",
            host,
            port,
            _SENTINEL_LOG_FILE,
        )

        try:
            proc = subprocess.Popen(
                [
                    sys.executable,
                    "-m",
                    "quota_sentinel.cli",
                    "start",
                    "--host",
                    host,
                    "--port",
                    str(port),
                ],
                stdout=log_fh,
                stderr=log_fh,
                start_new_session=True,  # detach from our process group
            )
        except (FileNotFoundError, OSError) as e:
            logger.error("Failed to spawn quota-sentinel server: %s", e)
            log_fh.close()
            return False

        _SENTINEL_PID_FILE.write_text(f"{proc.pid}\n")
        logger.info("Quota Sentinel spawned (PID %d)", proc.pid)
        log_fh.close()

        # Wait for it to accept connections
        deadline = time.monotonic() + _SENTINEL_START_TIMEOUT
        while time.monotonic() < deadline:
            time.sleep(1)
            if self._sentinel_available():
                logger.info("Quota Sentinel is up")
                return True
            # Check it hasn't already crashed
            if proc.poll() is not None:
                logger.error(
                    "Quota Sentinel exited immediately (rc=%d) — check %s",
                    proc.returncode,
                    _SENTINEL_LOG_FILE,
                )
                _SENTINEL_PID_FILE.unlink(missing_ok=True)
                return False

        logger.error(
            "Quota Sentinel did not start within %ds — check %s",
            _SENTINEL_START_TIMEOUT,
            _SENTINEL_LOG_FILE,
        )
        return False

    # ── Sentinel API ──────────────────────────────────────────────────

    def _sentinel_available(self) -> bool:
        try:
            _http(f"{self.sentinel_url}/v1/health", timeout=3)
            return True
        except Exception:  # noqa: BLE001
            return False

    def _register(self) -> bool:
        try:
            resp = _http(
                f"{self.sentinel_url}/v1/instances",
                method="POST",
                body={
                    "project_name": f"switcher:{self.opencode_json.parent.name}",
                    "framework": "opencode",
                    "poll_interval": self.poll_interval,
                    "auth": self._build_auth(),
                },
            )
            self._instance_id = resp["instance_id"]
            self._api_key = resp["api_key"]
            logger.info(
                "Registered with Quota Sentinel (instance %s)", self._instance_id
            )
            return True
        except Exception as e:  # noqa: BLE001
            logger.warning("Sentinel registration failed: %s", e)
            return False

    def _deregister(self) -> None:
        if not self._instance_id:
            return
        try:
            _http(
                f"{self.sentinel_url}/v1/instances/{self._instance_id}",
                method="DELETE",
            )
        except Exception:  # noqa: BLE001
            pass

    def _heartbeat(self) -> None:
        if not (self._instance_id and self._api_key):
            return
        try:
            _http(
                f"{self.sentinel_url}/v1/instances/{self._instance_id}/heartbeat",
                method="PATCH",
                body={"state": "active"},
                headers={"X-API-Key": self._api_key},
            )
        except Exception as e:  # noqa: BLE001
            logger.debug("Heartbeat failed: %s", e)

    def _get_provider_statuses(self) -> dict[str, str]:
        """Return {provider_name: 'GREEN'|'YELLOW'|'RED'} from Sentinel."""
        if not self._api_key:
            return {}
        try:
            data = _http(
                f"{self.sentinel_url}/v1/providers",
                headers={"X-API-Key": self._api_key},
            )
            return {
                name: pdata.get("status", "UNKNOWN") for name, pdata in data.items()
            }
        except Exception as e:  # noqa: BLE001
            logger.warning("Failed to get provider statuses: %s", e)
            return {}

    # ── Switching logic ───────────────────────────────────────────────

    @staticmethod
    def _provider(model_id: str) -> str:
        return model_id.split("/")[0] if "/" in model_id else model_id

    def _best_model(
        self,
        agent_name: str,
        agent_cfg: dict[str, Any],
        provider_statuses: dict[str, str],
    ) -> str | None:
        """Return the model this agent should use, or None if no change needed."""
        original = self.state.original_models.get(agent_name, "")
        current = self.state.active_models.get(agent_name, original)
        fallbacks: list[str] = agent_cfg.get("fallback_models", [])

        original_provider = self._provider(original)
        original_status = provider_statuses.get(original_provider, "GREEN")

        # Update recovery counter for original provider
        if original_status == "GREEN":
            self._recovery_counter[original_provider] = (
                self._recovery_counter.get(original_provider, 0) + 1
            )
        else:
            self._recovery_counter[original_provider] = 0

        on_fallback = current != original

        # Case 1: original provider healthy and we held long enough → restore
        if original_status == "GREEN" and on_fallback:
            if self._recovery_counter.get(original_provider, 0) >= self.recovery_hold:
                if current != original:
                    return original
            return None  # waiting for recovery hold

        # Case 2: original provider unhealthy → find best GREEN fallback
        if original_status in ("YELLOW", "RED"):
            for fallback in fallbacks:
                fb_provider = self._provider(fallback)
                if provider_statuses.get(fb_provider, "GREEN") == "GREEN":
                    if current != fallback:
                        return fallback
                    return None  # already on this fallback
            # All fallbacks also unhealthy — stay where we are
            return None

        # Case 3: original provider GREEN and we're already on original → nothing to do
        return None

    def _apply_switches(self, provider_statuses: dict[str, str]) -> int:
        """Apply model switches to opencode.json. Returns number of changes."""
        config = self._read_config()
        agents = config.get("agent", {})
        changes = 0

        for agent_name, agent_cfg in agents.items():
            if agent_name not in self.state.original_models:
                continue

            target = self._best_model(agent_name, agent_cfg, provider_statuses)
            if target is None:
                continue

            current = self.state.active_models.get(agent_name, "")
            original = self.state.original_models.get(agent_name, "")
            direction = (
                "→ original"
                if target == original
                else f"→ fallback ({self._provider(target)})"
            )

            logger.info(
                "  %s: %s %s (%s)",
                agent_name,
                current,
                direction,
                target,
            )

            agents[agent_name]["model"] = target
            self.state.active_models[agent_name] = target
            self.state.switched_at[agent_name] = datetime.now(UTC).isoformat()
            changes += 1

        if changes:
            self._write_config(config)
            self.state.save(self.state_path)

        return changes

    # ── Run loop ──────────────────────────────────────────────────────

    def poll_once(self) -> dict[str, Any]:
        """Run one check cycle. Returns a status summary."""
        provider_statuses = self._get_provider_statuses()
        changes = self._apply_switches(provider_statuses) if provider_statuses else 0

        # Build summary
        unhealthy = {p: s for p, s in provider_statuses.items() if s != "GREEN"}
        on_fallback = {
            name: model
            for name, model in self.state.active_models.items()
            if model != self.state.original_models.get(name)
        }

        summary = {
            "timestamp": datetime.now(UTC).isoformat(),
            "provider_statuses": provider_statuses,
            "unhealthy_providers": unhealthy,
            "agents_on_fallback": on_fallback,
            "changes_applied": changes,
        }

        if unhealthy:
            logger.warning(
                "Unhealthy providers: %s | Agents on fallback: %d",
                ", ".join(f"{p}={s}" for p, s in unhealthy.items()),
                len(on_fallback),
            )
        else:
            logger.info(
                "All providers GREEN | Agents on fallback: %d", len(on_fallback)
            )

        return summary

    def run(self) -> None:
        """Run the model switcher daemon."""
        if not self._sentinel_available():
            logger.info("Quota Sentinel not running — attempting auto-start")
            if not self._ensure_server_running():
                logger.error("Could not reach or start Quota Sentinel — aborting")
                return

        self._init_state()

        if not self._register():
            logger.error("Could not register with Quota Sentinel — aborting")
            return

        stop = [False]

        def _term(_s: int, _f: object) -> None:
            stop[0] = True
            logger.info("SIGTERM — shutting down")

        signal.signal(signal.SIGTERM, _term)
        signal.signal(signal.SIGINT, _term)

        logger.info(
            "Model switcher started | project=%s | sentinel=%s | poll=%ds | recovery_hold=%d",
            self.opencode_json.parent.name,
            self.sentinel_url,
            self.poll_interval,
            self.recovery_hold,
        )

        try:
            while not stop[0]:
                try:
                    self.poll_once()
                except Exception:  # noqa: BLE001
                    logger.exception("Poll cycle failed")

                self._heartbeat()

                for _ in range(self.poll_interval):
                    if stop[0]:
                        break
                    time.sleep(1)
        finally:
            self._deregister()
            logger.info("Model switcher stopped")

    def restore_all(self) -> int:
        """Restore all agents to their original models unconditionally."""
        config = self._read_config()
        agents = config.get("agent", {})
        changes = 0
        for agent_name, original in self.state.original_models.items():
            if agent_name in agents and agents[agent_name].get("model") != original:
                agents[agent_name]["model"] = original
                self.state.active_models[agent_name] = original
                logger.info("  %s: restored to %s", agent_name, original)
                changes += 1
        if changes:
            self._write_config(config)
            self.state.save(self.state_path)
        return changes
