#!/usr/bin/env python3
"""Token watchdog — standalone daemon generated by AgentCaddy.

Monitors provider token usage, tracks consumption velocity, and writes
TOKEN_STATUS.json for Ralph to read at the start of each iteration.

No external dependencies — uses stdlib only (urllib, json, etc.).
"""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import logging
import os
import signal
import subprocess
import time
import urllib.error
import urllib.request
from abc import ABC, abstractmethod
from collections import deque
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger("watchdog")

# Default path to opencode auth.json
_DEFAULT_OC_AUTH = str(
    Path.home() / ".local" / "share" / "opencode" / "auth.json",
)


# ═══════════════════════════════════════════════════════════════════════
# Data types
# ═══════════════════════════════════════════════════════════════════════


@dataclass
class WindowUsage:
    utilization: float
    resets_at: datetime | None = None


@dataclass
class UsageResult:
    provider: str
    windows: dict[str, WindowUsage] = field(default_factory=dict)
    error: str | None = None


# ═══════════════════════════════════════════════════════════════════════
# HTTP helpers
# ═══════════════════════════════════════════════════════════════════════


_UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)


def _http_get(
    url: str, headers: dict[str, str], timeout: int = 10,
) -> dict[str, Any]:
    hdrs = {"User-Agent": _UA}
    hdrs.update(headers)
    req = urllib.request.Request(url, headers=hdrs, method="GET")
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode())


def _http_post_json(
    url: str,
    body: dict,
    headers: dict[str, str] | None = None,
    timeout: int = 10,
) -> dict[str, Any]:
    data = json.dumps(body).encode()
    hdrs = {"Content-Type": "application/json", "User-Agent": _UA}
    if headers:
        hdrs.update(headers)
    req = urllib.request.Request(url, data=data, headers=hdrs, method="POST")
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode())


def _read_oc_auth(
    auth_path: str | None = None,
) -> dict[str, Any]:
    """Read opencode auth.json, return full dict or empty on error."""
    p = Path(auth_path or _DEFAULT_OC_AUTH)
    try:
        with open(p) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}


def _oc_key(auth: dict, *key_names: str) -> str:
    """Extract first available API key from auth dict."""
    for k in key_names:
        if auth.get(k, {}).get("key"):
            return auth[k]["key"]
    return ""


# ═══════════════════════════════════════════════════════════════════════
# Usage providers
# ═══════════════════════════════════════════════════════════════════════


class UsageProvider(ABC):
    name: str = "unknown"

    @abstractmethod
    def fetch(self) -> UsageResult: ...


class ClaudeUsageProvider(UsageProvider):
    name = "claude"
    USAGE_URL = "https://api.anthropic.com/api/oauth/usage"
    REFRESH_URL = "https://platform.claude.com/v1/oauth/token"
    CLIENT_ID = "9d1c250a-e61b-44d9-88ed-5944d1962f5e"

    def __init__(self, credentials_path: str | None = None):
        self.creds_path = Path(
            credentials_path or (Path.home() / ".claude" / ".credentials.json"),
        )

    def fetch(self) -> UsageResult:
        oauth = self._load_creds()
        if not oauth:
            return UsageResult(provider=self.name, error="no credentials")
        if time.time() * 1000 >= oauth.get("expiresAt", 0):
            oauth = self._refresh(oauth)
            if not oauth:
                return UsageResult(provider=self.name, error="token refresh failed")
        try:
            data = _http_get(self.USAGE_URL, headers={
                "Authorization": f"Bearer {oauth['accessToken']}",
                "anthropic-beta": "oauth-2025-04-20",
            })
        except urllib.error.HTTPError as e:
            return UsageResult(provider=self.name, error=f"HTTP {e.code}")
        except Exception as e:  # noqa: BLE001
            return UsageResult(provider=self.name, error=str(e))

        windows: dict[str, WindowUsage] = {}
        for key in ("five_hour", "seven_day", "seven_day_sonnet", "seven_day_opus"):
            b = data.get(key, {})
            if b:
                ra = None
                if b.get("resets_at"):
                    try:
                        ra = datetime.fromisoformat(b["resets_at"])
                    except (ValueError, TypeError):
                        pass
                windows[key] = WindowUsage(
                    float(b.get("utilization", 0) or 0), ra,
                )
        return UsageResult(provider=self.name, windows=windows)

    def _load_creds(self) -> dict | None:
        try:
            fd = open(self.creds_path)  # noqa: SIM115
            fcntl.flock(fd, fcntl.LOCK_SH)
            try:
                creds = json.load(fd)
            finally:
                fcntl.flock(fd, fcntl.LOCK_UN)
                fd.close()
            o = creds.get("claudeAiOauth", {})
            return o if o.get("accessToken") else None
        except (OSError, json.JSONDecodeError, KeyError):
            return None

    def _refresh(self, oauth: dict) -> dict | None:
        rt = oauth.get("refreshToken")
        if not rt:
            return None
        try:
            data = _http_post_json(self.REFRESH_URL, {
                "grant_type": "refresh_token",
                "refresh_token": rt,
                "client_id": self.CLIENT_ID,
            })
            fd = open(self.creds_path, "r+")  # noqa: SIM115
            fcntl.flock(fd, fcntl.LOCK_EX)
            try:
                creds = json.load(fd)
                creds["claudeAiOauth"]["accessToken"] = data["access_token"]
                creds["claudeAiOauth"]["refreshToken"] = data["refresh_token"]
                creds["claudeAiOauth"]["expiresAt"] = (
                    int(time.time() * 1000) + data.get("expires_in", 3600) * 1000
                )
                fd.seek(0)
                fd.truncate()
                json.dump(creds, fd, indent=2)
            finally:
                fcntl.flock(fd, fcntl.LOCK_UN)
                fd.close()
            return creds["claudeAiOauth"]
        except (OSError, json.JSONDecodeError, KeyError, urllib.error.HTTPError):
            return None


class CopilotUsageProvider(UsageProvider):
    name = "copilot"
    PLANS = {"free": 50, "pro": 300, "pro_plus": 1500}

    def __init__(
        self,
        github_username: str,
        github_token: str | None = None,
        plan: str = "pro",
    ):
        self.username = github_username
        self.token = github_token or ""
        if plan in self.PLANS:
            self.allowance = self.PLANS[plan]
        elif plan.isdigit():
            self.allowance = int(plan)
        else:
            self.allowance = 300

    def fetch(self) -> UsageResult:
        token = self.token or self._gh_token()
        if not token:
            return UsageResult(provider=self.name, error="no token")
        if not self.username:
            return UsageResult(provider=self.name, error="no username")
        now = datetime.now(UTC)
        url = (
            f"https://api.github.com/users/{self.username}"
            f"/settings/billing/premium_request/usage"
            f"?year={now.year}&month={now.month}"
        )
        try:
            data = _http_get(url, headers={
                "Accept": "application/vnd.github+json",
                "Authorization": f"Bearer {token}",
                "X-GitHub-Api-Version": "2026-03-10",
            })
        except urllib.error.HTTPError as e:
            error_map = {
                401: "auth failed",
                403: "no permission",
                429: "rate limited",
            }
            return UsageResult(
                provider=self.name,
                error=error_map.get(e.code, f"HTTP {e.code}"),
            )
        except Exception as e:  # noqa: BLE001
            return UsageResult(provider=self.name, error=str(e))

        used = sum(i.get("grossQuantity", 0) for i in data.get("usageItems", []))
        pct = (used / self.allowance * 100) if self.allowance else 0
        if now.month == 12:
            reset = datetime(now.year + 1, 1, 1, tzinfo=UTC)
        else:
            reset = datetime(now.year, now.month + 1, 1, tzinfo=UTC)
        return UsageResult(
            provider=self.name,
            windows={"monthly": WindowUsage(min(pct, 100), reset)},
        )

    def _gh_token(self) -> str:
        try:
            r = subprocess.run(
                ["gh", "auth", "token"],
                capture_output=True, text=True, timeout=5,
            )
            return r.stdout.strip() if r.returncode == 0 else ""
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return ""


class ZaiUsageProvider(UsageProvider):
    name = "zai"
    QUOTA_URL = "https://api.z.ai/api/monitor/usage/quota/limit"
    UNITS = {3: "hours", 5: "mcp", 6: "days"}

    def __init__(
        self,
        api_token: str | None = None,
        opencode_auth_path: str | None = None,
    ):
        self.api_token = api_token or ""
        self.auth_path = opencode_auth_path or _DEFAULT_OC_AUTH

    def fetch(self) -> UsageResult:
        token = self.api_token or _oc_key(
            _read_oc_auth(self.auth_path), "zai-coding-plan", "zai",
        )
        if not token:
            return UsageResult(provider=self.name, error="no token")
        try:
            data = _http_get(
                self.QUOTA_URL,
                headers={"Authorization": f"Bearer {token}"},
            )
        except urllib.error.HTTPError as e:
            error_map = {401: "auth failed", 429: "rate limited"}
            return UsageResult(
                provider=self.name,
                error=error_map.get(e.code, f"HTTP {e.code}"),
            )
        except Exception as e:  # noqa: BLE001
            return UsageResult(provider=self.name, error=str(e))

        if not data.get("success"):
            return UsageResult(provider=self.name, error="API returned success=false")
        windows: dict[str, WindowUsage] = {}
        for lim in data.get("data", {}).get("limits", []):
            if lim.get("type") != "TOKENS_LIMIT":
                continue
            unit = lim.get("unit", 0)
            number = lim.get("number", "?")
            wname = f"{number}{self.UNITS.get(unit, f'u{unit}')}"
            ra = None
            if lim.get("nextResetTime"):
                try:
                    ra = datetime.fromtimestamp(
                        lim["nextResetTime"] / 1000, tz=UTC,
                    )
                except (ValueError, TypeError, OSError):
                    pass
            windows[wname] = WindowUsage(
                float(lim.get("percentage", 0) or 0), ra,
            )
        return UsageResult(provider=self.name, windows=windows)


class MiniMaxUsageProvider(UsageProvider):
    """MiniMax coding plan — per-model interval + weekly quotas."""

    name = "minimax"
    REMAINS_URL = "https://platform.minimax.io/v1/api/openplatform/coding_plan/remains"

    def __init__(
        self,
        api_token: str | None = None,
        group_id: str | None = None,
        opencode_auth_path: str | None = None,
    ):
        self.api_token = api_token or ""
        self.group_id = group_id or ""
        self.auth_path = opencode_auth_path or _DEFAULT_OC_AUTH

    def fetch(self) -> UsageResult:
        token = self.api_token or _oc_key(
            _read_oc_auth(self.auth_path), "minimax-coding-plan", "minimax",
        )
        if not token:
            return UsageResult(provider=self.name, error="no token")
        if not self.group_id:
            return UsageResult(provider=self.name, error="no group_id")

        url = f"{self.REMAINS_URL}?GroupId={self.group_id}"
        try:
            data = _http_get(url, headers={
                "accept": "application/json, text/plain, */*",
                "authorization": f"Bearer {token}",
                "referer": "https://platform.minimax.io/user-center/payment/coding-plan",
            })
        except urllib.error.HTTPError as e:
            error_map = {401: "auth failed", 429: "rate limited"}
            return UsageResult(
                provider=self.name,
                error=error_map.get(e.code, f"HTTP {e.code}"),
            )
        except Exception as e:  # noqa: BLE001
            return UsageResult(provider=self.name, error=str(e))

        status_code = data.get("base_resp", {}).get("status_code", -1)
        if status_code != 0:
            msg = data.get("base_resp", {}).get("status_msg", "unknown")
            return UsageResult(provider=self.name, error=f"API: {msg}")

        windows: dict[str, WindowUsage] = {}
        for model in data.get("model_remains", []):
            mname = model.get("model_name", "?")
            # Skip non-text models (video, audio, image, music)
            lower = mname.lower()
            if any(kw in lower for kw in (
                "hailuo", "speech", "music", "image", "video", "audio",
            )):
                continue
            # Shorten model names
            short = mname.replace("MiniMax-", "MM-").replace("minimax-", "mm-")

            # Interval quota
            total = model.get("current_interval_total_count", 0)
            remaining = model.get("current_interval_usage_count", 0)
            if total > 0:
                used = total - remaining
                pct = used / total * 100
                ra = self._reset_time(model.get("remains_time", 0))
                windows[f"{short}_interval"] = WindowUsage(min(pct, 100), ra)

            # Weekly quota
            wtotal = model.get("current_weekly_total_count", 0)
            if wtotal > 0:
                wremaining = model.get("current_weekly_usage_count", 0)
                wused = wtotal - wremaining
                wpct = wused / wtotal * 100
                wra = self._reset_time(model.get("weekly_remains_time", 0))
                windows[f"{short}_weekly"] = WindowUsage(min(wpct, 100), wra)

        return UsageResult(provider=self.name, windows=windows)

    @staticmethod
    def _reset_time(remains_ms: int) -> datetime | None:
        """Convert remaining-ms to an absolute reset datetime."""
        if remains_ms <= 0:
            return None
        return datetime.fromtimestamp(
            time.time() + remains_ms / 1000, tz=UTC,
        )


class DeepSeekUsageProvider(UsageProvider):
    """DeepSeek — balance-based (not percentage).

    We convert balance to a pseudo-utilization: 100 - (balance / ref * 100).
    ref defaults to the first observed balance (or 10 if unknown).
    """

    name = "deepseek"
    BALANCE_URL = "https://api.deepseek.com/user/balance"

    def __init__(
        self,
        api_token: str | None = None,
        opencode_auth_path: str | None = None,
        reference_balance: float | None = None,
    ):
        self.api_token = api_token or ""
        self.auth_path = opencode_auth_path or _DEFAULT_OC_AUTH
        self._ref_balance = reference_balance

    def fetch(self) -> UsageResult:
        token = self.api_token or _oc_key(
            _read_oc_auth(self.auth_path), "deepseek-coding-plan", "deepseek",
        )
        if not token:
            return UsageResult(provider=self.name, error="no token")
        try:
            data = _http_get(
                self.BALANCE_URL,
                headers={"Authorization": f"Bearer {token}"},
            )
        except urllib.error.HTTPError as e:
            error_map = {401: "auth failed", 429: "rate limited"}
            return UsageResult(
                provider=self.name,
                error=error_map.get(e.code, f"HTTP {e.code}"),
            )
        except Exception as e:  # noqa: BLE001
            return UsageResult(provider=self.name, error=str(e))

        balances = data.get("balance_infos", [])
        if not balances:
            return UsageResult(provider=self.name, error="no balance data")

        bal = balances[0]
        total = float(bal.get("total_balance", "0"))
        is_available = data.get("is_available", total > 0)

        # Use first observed balance as reference for percentage
        if self._ref_balance is None:
            self._ref_balance = max(total, 10.0)
        ref = self._ref_balance

        pct = max(0.0, 100.0 - (total / ref * 100)) if ref > 0 else 0.0
        if not is_available:
            pct = 100.0

        return UsageResult(
            provider=self.name,
            windows={
                "balance": WindowUsage(
                    utilization=min(pct, 100.0),
                    resets_at=None,  # balance doesn't reset
                ),
            },
        )


class AlibabaUsageProvider(UsageProvider):
    """Alibaba Cloud (Tongyi Lingma) coding plan — 5h/weekly/monthly quotas.

    Uses undocumented console RPC endpoint (reverse-engineered by CodexBar).
    """

    name = "alibaba"
    REGIONS = {
        "intl": {
            "host": "https://modelstudio.console.alibabacloud.com",
            "region_id": "ap-southeast-1",
            "commodity_code": "sfm_codingplan_public_intl",
        },
        "cn": {
            "host": "https://bailian.console.aliyun.com",
            "region_id": "cn-beijing",
            "commodity_code": "sfm_codingplan_public_cn",
        },
    }

    def __init__(
        self,
        api_token: str | None = None,
        opencode_auth_path: str | None = None,
        region: str = "intl",
    ):
        self.api_token = api_token or ""
        self.auth_path = opencode_auth_path or _DEFAULT_OC_AUTH
        self.region = region

    def fetch(self) -> UsageResult:
        token = self.api_token or _oc_key(
            _read_oc_auth(self.auth_path),
            "bailian-coding-plan", "alibaba-coding-plan", "dashscope", "alibaba",
        )
        if not token:
            return UsageResult(provider=self.name, error="no token")

        rcfg = self.REGIONS.get(self.region, self.REGIONS["intl"])
        url = (
            f"{rcfg['host']}/data/api.json"
            f"?action=zeldaEasy.broadscope-bailian.codingPlan"
            f".queryCodingPlanInstanceInfoV2"
            f"&product=broadscope-bailian"
            f"&api=queryCodingPlanInstanceInfoV2"
            f"&currentRegionId={rcfg['region_id']}"
        )
        body = {
            "queryCodingPlanInstanceInfoRequest": {
                "commodityCode": rcfg["commodity_code"],
            },
        }
        try:
            data = _http_post_json(url, body, headers={
                "Authorization": f"Bearer {token}",
                "x-api-key": token,
                "X-DashScope-API-Key": token,
            }, timeout=15)
        except urllib.error.HTTPError as e:
            error_map = {401: "auth failed", 429: "rate limited"}
            return UsageResult(
                provider=self.name,
                error=error_map.get(e.code, f"HTTP {e.code}"),
            )
        except Exception as e:  # noqa: BLE001
            return UsageResult(provider=self.name, error=str(e))

        if data.get("code") == "ConsoleNeedLogin":
            return UsageResult(provider=self.name, error="ConsoleNeedLogin")

        quota_info = self._find_quota(data)
        if not quota_info:
            return UsageResult(provider=self.name, error="no quota data")

        windows: dict[str, WindowUsage] = {}
        for label, prefix in [
            ("5h", "per5Hour"),
            ("weekly", "perWeek"),
            ("monthly", "perBillMonth"),
        ]:
            used = quota_info.get(f"{prefix}UsedQuota")
            total = quota_info.get(f"{prefix}TotalQuota")
            if total is not None and used is not None and int(total) > 0:
                pct = int(used) / int(total) * 100
                ra = None
                rt = quota_info.get(f"{prefix}QuotaNextRefreshTime")
                if rt:
                    ra = self._parse_reset(rt)
                windows[label] = WindowUsage(min(pct, 100), ra)

        return UsageResult(provider=self.name, windows=windows)

    @staticmethod
    def _parse_reset(value: Any) -> datetime | None:
        """Parse reset time from epoch-ms or ISO string."""
        try:
            if isinstance(value, (int, float)):
                return datetime.fromtimestamp(value / 1000, tz=UTC)
            dt = datetime.fromisoformat(str(value))
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=UTC)
            return dt
        except (ValueError, TypeError, OSError):
            return None

    @staticmethod
    def _find_quota(data: dict) -> dict | None:
        """Navigate nested response to find codingPlanQuotaInfo."""
        # Try standard paths
        for root in [
            data,
            data.get("data", {}),
            data.get("data", {}).get("result", {}),
            data.get("result", {}),
        ]:
            if not isinstance(root, dict):
                continue
            instances = root.get("codingPlanInstanceInfos")
            if isinstance(instances, list) and instances:
                inst = instances[0]
                return inst.get("codingPlanQuotaInfo", inst)
        # Fallback: recursive search for quota fields
        return AlibabaUsageProvider._search_quota(data, depth=0)

    @staticmethod
    def _search_quota(obj: Any, depth: int) -> dict | None:
        if depth > 5 or not isinstance(obj, dict):
            return None
        if "per5HourTotalQuota" in obj:
            return obj
        for v in obj.values():
            if isinstance(v, dict):
                result = AlibabaUsageProvider._search_quota(v, depth + 1)
                if result:
                    return result
            elif isinstance(v, list):
                for item in v:
                    if isinstance(item, dict):
                        result = AlibabaUsageProvider._search_quota(
                            item, depth + 1,
                        )
                        if result:
                            return result
        return None


# ═══════════════════════════════════════════════════════════════════════
# Provider registry
# ═══════════════════════════════════════════════════════════════════════

PROVIDER_CLASSES = {
    "claude": ClaudeUsageProvider,
    "copilot": CopilotUsageProvider,
    "zai": ZaiUsageProvider,
    "minimax": MiniMaxUsageProvider,
    "deepseek": DeepSeekUsageProvider,
    "alibaba": AlibabaUsageProvider,
}


def create_provider(name: str, config: dict) -> UsageProvider:
    if name == "claude":
        return ClaudeUsageProvider(config.get("credentials_path"))
    if name == "copilot":
        return CopilotUsageProvider(
            config.get("github_username", ""),
            config.get("github_token"),
            config.get("plan", "pro"),
        )
    if name == "zai":
        return ZaiUsageProvider(
            config.get("api_token"),
            config.get("opencode_auth_path"),
        )
    if name == "minimax":
        return MiniMaxUsageProvider(
            config.get("api_token"),
            config.get("group_id"),
            config.get("opencode_auth_path"),
        )
    if name == "deepseek":
        return DeepSeekUsageProvider(
            config.get("api_token"),
            config.get("opencode_auth_path"),
            config.get("reference_balance"),
        )
    if name == "alibaba":
        return AlibabaUsageProvider(
            config.get("api_token"),
            config.get("opencode_auth_path"),
            config.get("region", "intl"),
        )
    raise ValueError(f"Unknown provider: {name}")


# ═══════════════════════════════════════════════════════════════════════
# Velocity tracking + evaluation
# ═══════════════════════════════════════════════════════════════════════


class VelocityTracker:
    def __init__(self, max_samples: int = 10):
        self._samples: deque[tuple[float, float]] = deque(maxlen=max_samples)

    def add(self, utilization: float) -> None:
        self._samples.append((time.time(), utilization))

    def velocity(self) -> float:
        if len(self._samples) < 2:
            return 0.0
        n = len(self._samples)
        t_m = sum(s[0] for s in self._samples) / n
        u_m = sum(s[1] for s in self._samples) / n
        num = sum((s[0] - t_m) * (s[1] - u_m) for s in self._samples)
        den = sum((s[0] - t_m) ** 2 for s in self._samples)
        return max((num / den * 3600) if den else 0.0, 0.0)

    def exhaustion_min(self, current: float, cap: float) -> float | None:
        if current >= cap:
            return 0.0
        v = self.velocity()
        return ((cap - current) / v * 60) if v > 0 else None


def _get_cap(provider: str, window: str, caps: dict[str, float]) -> float:
    return caps.get(f"{provider}_{window}", caps.get(f"{provider}_default", 85.0))


def _window_status(
    util: float, vel: float, cap: float, margin_min: float,
) -> str:
    if util >= cap:
        return "RED"
    buf = vel * (margin_min / 60)
    thresh = cap - buf
    if util >= thresh:
        if vel > 0 and ((cap - util) / vel * 60) <= margin_min:
            return "RED"
        return "YELLOW"
    return "GREEN"


def evaluate(
    results: dict[str, UsageResult],
    velocities: dict[str, dict[str, VelocityTracker]],
    framework: str,
    caps: dict[str, float],
    margin: float,
) -> dict:
    prov_out: dict[str, Any] = {}
    order = {"GREEN": 0, "YELLOW": 1, "RED": 2}
    worst = "GREEN"
    msgs: list[str] = []

    for pname, res in results.items():
        if res.error:
            prov_out[pname] = {"status": "UNKNOWN", "error": res.error}
            continue
        pw = "GREEN"
        wout: dict[str, Any] = {}
        for wn, wd in res.windows.items():
            tr = velocities.get(pname, {}).get(wn)
            v = tr.velocity() if tr else 0.0
            c = _get_cap(pname, wn, caps)
            ws = _window_status(wd.utilization, v, c, margin)
            em = tr.exhaustion_min(wd.utilization, c) if tr else None
            wout[wn] = {
                "utilization": round(wd.utilization, 1),
                "velocity_pct_per_hour": round(v, 1),
                "projected_exhaustion_min": round(em) if em is not None else None,
                "resets_at": wd.resets_at.isoformat() if wd.resets_at else None,
                "status": ws,
            }
            if order.get(ws, 0) > order.get(pw, 0):
                pw = ws
            if ws in ("YELLOW", "RED"):
                t = f"~{round(em)}min" if em is not None else "growing"
                msgs.append(f"{pname} {wn} at {wd.utilization:.0f}% ({t})")
        prov_out[pname] = {"status": pw, "windows": wout}
        if order.get(pw, 0) > order.get(worst, 0):
            worst = pw

    active = [p for p, r in results.items() if not r.error]
    reds = [p for p in active if prov_out.get(p, {}).get("status") == "RED"]
    greens = [p for p in active if prov_out.get(p, {}).get("status") == "GREEN"]
    all_exhausted = len(reds) == len(active) > 0

    if framework == "claude":
        if worst == "RED":
            rec = "STOP"
        elif worst == "YELLOW":
            rec = "PROCEED_SMALL_ONLY"
        else:
            rec = "PROCEED"
    else:
        if all_exhausted:
            rec = "STOP"
        elif worst == "RED" and greens:
            rec = "PROCEED"
            msgs.append(f"OpenCode auto-retry: {', '.join(greens)}")
        elif worst == "YELLOW":
            rec = "PROCEED_SMALL_ONLY"
        else:
            rec = "PROCEED"

    return {
        "timestamp": datetime.now(UTC).isoformat(),
        "framework": framework,
        "overall_status": worst,
        "recommendation": rec,
        "message": "; ".join(msgs) or "All providers healthy",
        "providers": prov_out,
        "alternative_providers": sorted(greens),
        "all_exhausted": all_exhausted,
    }


# ═══════════════════════════════════════════════════════════════════════
# Daemon
# ═══════════════════════════════════════════════════════════════════════


# Maps auth.json key names → watchdog provider name
_AUTH_KEY_TO_PROVIDER: dict[str, str] = {
    "zai-coding-plan": "zai",
    "zai": "zai",
    "github-copilot": "copilot",
    "minimax-coding-plan": "minimax",
    "minimax": "minimax",
    "deepseek-coding-plan": "deepseek",
    "deepseek": "deepseek",
    "bailian-coding-plan": "alibaba",
    "alibaba-coding-plan": "alibaba",
    "dashscope": "alibaba",
    "alibaba": "alibaba",
}


class TokenWatchdog:
    def __init__(self, config_path: str):
        config_abs = Path(config_path).resolve()
        with open(config_abs) as f:
            cfg = json.load(f)
        self.framework = cfg.get("framework", "opencode")
        self.poll_interval = max(int(cfg.get("poll_interval", 300)), 30)
        self.margin = int(cfg.get("safety_margin_min", 30))
        self.vel_window = int(cfg.get("velocity_window", 10))
        # Write status file relative to project root, not CWD
        self.project_dir = config_abs.parent.parent
        self.status_file = str(
            self.project_dir / cfg.get("status_file", "TOKEN_STATUS.json"),
        )
        self.caps = {
            "claude_five_hour": 80.0,
            "claude_seven_day": 90.0,
            "copilot_monthly": 85.0,
            "zai_default": 80.0,
            "minimax_default": 85.0,
            "deepseek_default": 85.0,
            "alibaba_default": 80.0,
        }
        self.caps.update(cfg.get("hard_caps", {}))

        # Auto-detect providers, then merge explicit config as overrides
        provider_cfgs = self._auto_detect_providers(cfg)
        logger.info("Auto-detected providers: %s", list(provider_cfgs.keys()))
        for pname, pcfg in cfg.get("providers", {}).items():
            if pname in provider_cfgs:
                provider_cfgs[pname].update(pcfg)
            else:
                provider_cfgs[pname] = pcfg

        # Auto-fill github username for copilot if missing
        if "copilot" in provider_cfgs and not provider_cfgs["copilot"].get(
            "github_username",
        ):
            username = self._detect_github_username()
            if username:
                provider_cfgs["copilot"]["github_username"] = username
                logger.info("Auto-detected GitHub user: %s", username)
            else:
                logger.warning(
                    "copilot: could not detect GitHub username. "
                    "Install gh CLI or set github_username in config.",
                )

        # Warn about incomplete provider configs
        self._warn_missing_config(provider_cfgs)

        self.providers: list[UsageProvider] = []
        self.velocities: dict[str, dict[str, VelocityTracker]] = {}
        for pname, pcfg in provider_cfgs.items():
            try:
                self.providers.append(create_provider(pname, pcfg))
                self.velocities[pname] = {}
            except ValueError as e:
                logger.warning("Skipping %s: %s", pname, e)

    @classmethod
    def _auto_detect_providers(cls, cfg: dict) -> dict[str, dict]:
        """Auto-detect providers from auth.json + Claude credentials.

        Scans opencode auth.json for any key that maps to a known provider.
        Also checks for Claude OAuth credentials separately.
        """
        provs: dict[str, dict] = {}

        # 1. Scan opencode auth.json for all providers with keys
        auth_path = cfg.get("opencode_auth_path") or _DEFAULT_OC_AUTH
        auth = _read_oc_auth(auth_path)
        for auth_key, entry in auth.items():
            if not isinstance(entry, dict) or not entry.get("key"):
                continue
            pname = _AUTH_KEY_TO_PROVIDER.get(auth_key)
            if pname and pname not in provs:
                pcfg: dict[str, Any] = {}
                if pname == "copilot":
                    pcfg = {"github_username": "", "plan": "pro"}
                elif pname == "minimax":
                    # MiniMax needs group_id — try to extract from auth
                    pcfg = {"group_id": entry.get("group_id", "")}
                provs[pname] = pcfg

        # 2. Check Claude OAuth credentials
        creds = Path.home() / ".claude" / ".credentials.json"
        if creds.exists() and "claude" not in provs:
            provs["claude"] = {}

        return provs

    @staticmethod
    def _warn_missing_config(provider_cfgs: dict[str, dict]) -> None:
        """Log warnings for providers that need extra configuration."""
        # Required fields per provider (field, hint)
        requirements: dict[str, list[tuple[str, str]]] = {
            "minimax": [
                ("group_id", (
                    "Get it from https://platform.minimax.io → user center. "
                    "Add to watchdog/config.json: "
                    '{"providers": {"minimax": {"group_id": "YOUR_ID"}}}'
                )),
            ],
            "copilot": [
                ("github_username", (
                    "Install gh CLI (https://cli.github.com) for auto-detection, "
                    "or add to watchdog/config.json: "
                    '{"providers": {"copilot": {"github_username": "YOU"}}}'
                )),
            ],
        }
        for pname, fields in requirements.items():
            if pname not in provider_cfgs:
                continue
            pcfg = provider_cfgs[pname]
            for field_name, hint in fields:
                if not pcfg.get(field_name):
                    logger.warning(
                        "%s: missing '%s' — provider will not work. %s",
                        pname, field_name, hint,
                    )

    @staticmethod
    def _detect_github_username() -> str:
        try:
            r = subprocess.run(
                ["gh", "api", "user", "--jq", ".login"],
                capture_output=True, text=True, timeout=5,
            )
            if r.returncode == 0 and r.stdout.strip():
                return r.stdout.strip()
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass
        return ""

    def poll_once(self) -> dict:
        results: dict[str, UsageResult] = {}
        for p in self.providers:
            res = p.fetch()
            results[p.name] = res
            if res.error:
                logger.warning("  %s: ERROR — %s", p.name, res.error)
            else:
                if p.name not in self.velocities:
                    self.velocities[p.name] = {}
                for wn, wd in res.windows.items():
                    if wn not in self.velocities[p.name]:
                        self.velocities[p.name][wn] = VelocityTracker(
                            self.vel_window,
                        )
                    self.velocities[p.name][wn].add(wd.utilization)

        status = evaluate(
            results, self.velocities, self.framework, self.caps, self.margin,
        )

        # Detailed per-provider log
        for pname, pdata in status["providers"].items():
            if pdata.get("error"):
                continue  # already logged above
            pstatus = pdata["status"]
            parts = []
            for wn, wd in pdata.get("windows", {}).items():
                vel = wd["velocity_pct_per_hour"]
                exh = wd["projected_exhaustion_min"]
                vel_str = f" +{vel:.1f}%/h" if vel > 0 else ""
                exh_str = f" exhaust ~{exh}min" if exh is not None else ""
                parts.append(
                    f"{wn}={wd['utilization']:.0f}%{vel_str}{exh_str}",
                )
            logger.info(
                "  %s: %s — %s", pname, pstatus, ", ".join(parts),
            )

        # Summary line
        logger.info(
            "=> %s — %s (%s)",
            status["overall_status"],
            status["recommendation"],
            status["message"],
        )

        sp = Path(self.status_file)
        tmp = sp.with_suffix(".tmp")
        tmp.write_text(json.dumps(status, indent=2) + "\n")
        tmp.rename(sp)
        return status

    # ── Central watchdog integration ────────────────────────────────

    _CENTRAL_DIR = Path.home() / ".agentcaddy" / "watchdog"
    _CENTRAL_PID = _CENTRAL_DIR / "central.pid"
    _INSTANCES_DIR = _CENTRAL_DIR / "instances"

    def _instance_id(self) -> str:
        """Deterministic ID from project directory."""
        return hashlib.sha256(
            str(self.project_dir).encode(),
        ).hexdigest()[:12]

    def _central_available(self) -> bool:
        """Check if a central watchdog daemon is running."""
        if not self._CENTRAL_PID.exists():
            return False
        try:
            pid = int(self._CENTRAL_PID.read_text().strip())
            os.kill(pid, 0)
            return True
        except (ValueError, OSError):
            return False

    def _central_pid(self) -> int | None:
        """Read the central watchdog PID."""
        try:
            return int(self._CENTRAL_PID.read_text().strip())
        except (ValueError, OSError, FileNotFoundError):
            return None

    def _register(self) -> None:
        """Register this instance with the central watchdog."""
        self._INSTANCES_DIR.mkdir(parents=True, exist_ok=True)
        data = {
            "instance_id": self._instance_id(),
            "project_dir": str(self.project_dir),
            "project_name": self.project_dir.name,
            "framework": self.framework,
            "pid": os.getpid(),
            "registered_at": datetime.now(UTC).isoformat(),
            "heartbeat_at": datetime.now(UTC).isoformat(),
            "state": "active",
            "status_file": self.status_file,
        }
        path = self._INSTANCES_DIR / f"{self._instance_id()}.json"
        path.write_text(json.dumps(data, indent=2) + "\n")
        logger.info("Registered with central watchdog: %s", self._instance_id())

    def _deregister(self) -> None:
        """Remove this instance's registration."""
        path = self._INSTANCES_DIR / f"{self._instance_id()}.json"
        path.unlink(missing_ok=True)
        logger.info("Deregistered from central watchdog")

    def _heartbeat(self, state: str = "active") -> None:
        """Update heartbeat timestamp in registration file."""
        path = self._INSTANCES_DIR / f"{self._instance_id()}.json"
        if not path.exists():
            self._register()
            return
        try:
            data = json.loads(path.read_text())
            data["heartbeat_at"] = datetime.now(UTC).isoformat()
            data["state"] = state
            data["pid"] = os.getpid()
            path.write_text(json.dumps(data, indent=2) + "\n")
        except (json.JSONDecodeError, OSError):
            self._register()

    def _forward_sigusr1(self) -> bool:
        """Forward SIGUSR1 to the central watchdog daemon."""
        cpid = self._central_pid()
        if cpid is None:
            return False
        try:
            os.kill(cpid, signal.SIGUSR1)
            logger.info("Forwarded SIGUSR1 to central watchdog (pid %d)", cpid)
            return True
        except OSError:
            return False

    # ── Run modes ────────────────────────────────────────────────────

    def run(self) -> None:
        """Run the watchdog — auto-selects local or client mode."""
        pid_file = Path(self.status_file).with_name("watchdog.pid")
        pid_file.write_text(str(os.getpid()) + "\n")

        poll_now = False
        stop = False

        def _handle_usr1(_signum: int, _frame: Any) -> None:
            nonlocal poll_now
            poll_now = True

        def _handle_term(_signum: int, _frame: Any) -> None:
            nonlocal stop
            stop = True
            logger.info("SIGTERM received — shutting down")

        signal.signal(signal.SIGUSR1, _handle_usr1)
        signal.signal(signal.SIGTERM, _handle_term)

        try:
            if self._central_available():
                self._run_client_mode(pid_file, poll_now, stop,
                                      lambda: poll_now, lambda: stop,
                                      lambda v: None)
            else:
                self._run_local_mode(pid_file, lambda: poll_now, lambda: stop)
        finally:
            pid_file.unlink(missing_ok=True)

    def _run_local_mode(
        self,
        pid_file: Path,
        get_poll_now: Any,
        get_stop: Any,
    ) -> None:
        """Standard local mode — polls APIs and writes TOKEN_STATUS.json."""
        logger.info(
            "Watchdog LOCAL: %d providers, poll %ds, framework=%s, pid=%d",
            len(self.providers), self.poll_interval, self.framework,
            os.getpid(),
        )
        check_central_counter = 0
        # Access nonlocal flags via closure trick
        poll_now_ref = [False]
        stop_ref = [False]

        # Re-wire signal handlers to use our refs
        def _usr1(_s: int, _f: Any) -> None:
            poll_now_ref[0] = True
            logger.info("SIGUSR1 received — scheduling immediate poll")

        def _term(_s: int, _f: Any) -> None:
            stop_ref[0] = True
            logger.info("SIGTERM received — shutting down")

        signal.signal(signal.SIGUSR1, _usr1)
        signal.signal(signal.SIGTERM, _term)

        while not stop_ref[0]:
            try:
                self.poll_once()
            except Exception:  # noqa: BLE001
                logger.exception("Poll failed")

            # Every 5 polls, check if central daemon appeared
            check_central_counter += 1
            if check_central_counter >= 5:
                check_central_counter = 0
                if self._central_available():
                    logger.info("Central watchdog detected — switching to client mode")
                    self._register()
                    self._run_client_loop(stop_ref, poll_now_ref)
                    return  # client mode ended (central died), exit

            for _ in range(self.poll_interval):
                if poll_now_ref[0] or stop_ref[0]:
                    poll_now_ref[0] = False
                    break
                time.sleep(1)

    def _run_client_mode(self, *_args: Any) -> None:
        """Entry point for client mode when central is detected at startup."""
        logger.info(
            "Watchdog CLIENT: project=%s, central pid=%s",
            self.project_dir.name, self._central_pid(),
        )
        self._register()

        stop_ref = [False]
        poll_now_ref = [False]

        def _usr1(_s: int, _f: Any) -> None:
            poll_now_ref[0] = True

        def _term(_s: int, _f: Any) -> None:
            stop_ref[0] = True
            logger.info("SIGTERM received — shutting down")

        signal.signal(signal.SIGUSR1, _usr1)
        signal.signal(signal.SIGTERM, _term)

        try:
            self._run_client_loop(stop_ref, poll_now_ref)
        finally:
            self._deregister()

    def _run_client_loop(
        self,
        stop_ref: list[bool],
        poll_now_ref: list[bool],
    ) -> None:
        """Client mode loop: heartbeat + forward signals, no API polling."""
        while not stop_ref[0]:
            # Update heartbeat
            self._heartbeat("active")

            # If SIGUSR1 received, forward to central
            if poll_now_ref[0]:
                poll_now_ref[0] = False
                if self._forward_sigusr1():
                    logger.info("SIGUSR1 forwarded to central — Ralph will read fresh status")
                else:
                    # Central died — fall back to local mode
                    logger.warning("Central watchdog unreachable — reverting to local mode")
                    return

            # Periodically check central is still alive
            if not self._central_available():
                logger.warning("Central watchdog gone — reverting to local mode")
                self._deregister()
                return

            for _ in range(self.poll_interval):
                if poll_now_ref[0] or stop_ref[0]:
                    break
                time.sleep(1)


# ═══════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        datefmt="%H:%M:%S",
    )
    ap = argparse.ArgumentParser(description="Token watchdog daemon")
    ap.add_argument("--config", required=True)
    ap.add_argument("--once", action="store_true")
    args = ap.parse_args()

    wd = TokenWatchdog(args.config)
    if args.once:
        print(json.dumps(wd.poll_once(), indent=2))
    else:
        wd.run()
